import * as React from "react";
import Head from "next/head";
import Button from "@mui/material/Button";
import TextField from "@mui/material/TextField";
import Grid from "@mui/material/Grid";
import Box from "@mui/material/Box";
import BasicSelect from "../components/Select/BasicSelect";
import ImageIcon from "@mui/icons-material/Image";
import CategoryTab from "../components/CategoryTab";
import DatePick from "../components/DatePick";

export default function Home() {
  //const theme = useTheme();

  return (
    <>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create-next-app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        container
        spacing={1}
        padding={1}
        flexGrow={1}
        maxWidth="sm"
        sx={{ width: "100%" }}
      >
        <Grid
          size={12}
          item
          container
          direction="row"
          sx={{
            justifyConten: "space-between",
            alignItems: "center",
          }}
        >
          <Box
            sx={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              width: "100%",
            }}
          >
            <Button variant="contained" color="error">
              取消
            </Button>
            <Button variant="contained">新增</Button>
          </Box>
        </Grid>

        <Grid size={12} item>
          <CategoryTab />
        </Grid>

        <Grid size={12} item>
          <TextField
            id="outlined-basic"
            label="名稱"
            variant="outlined"
            fullWidth
          />
        </Grid>

        <Grid size={6} item>
          <Button
            variant="outlined"
            startIcon={<ImageIcon />}
            sx={{ width: "100%", height: "100%" }}
          >
            上傳照片
          </Button>
        </Grid>
        <Grid item container size={6} rowSpacing={1} columnSpacing={1}>
          <Grid size={12} item>
            <BasicSelect />
          </Grid>
          <Grid size={12} item>
            <DatePick />
          </Grid>
        </Grid>

        <Grid size={12} item>
          <TextField
            id="outlined-multiline-static"
            label="備註"
            multiline
            rows={3}
            defaultValue="備註"
            fullWidth
          />
        </Grid>
      </Grid>
    </>
  );
}
